### ISSUE TITLE
Error on start mat theme

### ISSUE THREAD

**Issue by willy-wonka-git** [quasarframework/quasar-nuxt#1]
### Software version

quasar-nuxt:
OS:
Node:
NPM:
Browsers:
Any other software related to your bug:

### What did you get as the error?

 **nuxt:render Rendering url / +12s
{ TypeError: Cannot set property 'screen' of undefined
    at Object.install (node_modules/quasar-framework/dist/quasar.mat.esm.js:19632:0)
    at server-bundle.js:4509:11
    at Array.forEach (<anonymous>)
    at Object.install (node_modules/quasar-framework/dist/quasar.mat.esm.js:835:0)
    at Function.Vue.use (d:\Projects\_Workplace\schooling\nuxt\node_modules\vue\dist\vue.runtime.common.js:4749:22)
    at module.exports.__webpack_exports__.a (.nuxt/quasar-nuxt.js:15:0)
    at createApp (.nuxt/index.js:135:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) statusCode: 500, name: 'TypeError' }**

---------------------
install: function install (ref) {
    var this$1 = this;
    var $q = ref.$q;
    var Vue = ref.Vue;

    if (this.__installed) { return }
    this.__installed = true;

    if (isSSR) {
      **this.$q.screen = this;** => **$q.screen = this**
      this.setSizes = this.setDebounce = function () {};
      return
    }
---------------------------------------------------------------

{
  "dependencies": {
    "nuxt": "^1.0.0",
    "quasar-nuxt": "^0.16.0-alpha.2"
  },
  "devDependencies": {
    "babel-eslint": "^8.2.1",
    "eslint": "^4.15.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-vue": "^4.0.0"
  }
}

**Comment by rstoenescu** [comment]
Hi,

Thanks for your interest in Quasar and this Nuxt module. Unfortunately, it is still work in progress here (indicated on this repo), as you need the bleeding edge version of Quasar: v0.16.1, which I haven't released yet. Please stay tuned to our Discord/Forum/Twitter account for announcements ;)

**Comment by MarcWeber** [comment]
On discord I was told to use quasar's solution: https://quasar.dev/quasar-cli/developing-ssr/introduction
